### ISSUE TITLE
Cannot read property 'getBitmap' of null

### ISSUE THREAD

**Issue by standevo** [fthuin/nativescript-image-black-and-white#1]
Hi.. Thx for the plugin it's working but also in console I get the error (Android Emulator):

`ERROR TypeError: Cannot read property 'getBitmap' of null`

Another question:
How to revert back with colors after applying blackAndWhite method?

**Comment by fthuin** [comment]
Hi @csi-stasik!

Thank you for the feedback. I'll publish a new version soon (I hope before tomorrow) that fixes this error and allow to clearColorFilter, for android it's just `someImageVariable.android.clearColorFilter()` but I agree that it would be easier to have one in this plugin.
